[package]
name = "hiperjoy"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2.6.0"
enigo = "0.2.1"
gtk = { version = "0.8.2", package = "gtk4", features = ["v4_14"] }
leap-sys = "0.2.0"
num_enum = "0.7.2"
thiserror = "1.0.61"
