[package]
name = "hiperjoy"
version = "0.1.0"
edition = "2021"

[dependencies]
enigo = "0.2.1"
gtk = { version = "0.8.2", package = "gtk4", features = ["v4_14"] }

[build-dependencies]
bindgen = "0.64.0"
